### ISSUE TITLE
Support for Controlling the Brightness of the Flashlight						



### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Flashy#71] opened 2022-10-06 09:41 UTC
Some Samsung and Pixel phones are able to adjust the flashlight brightness using [`getTorchStrengthLevel`](https://developer.android.com/reference/android/hardware/camera2/CameraManager#getTorchStrengthLevel(java.lang.String)) and [`turnOnTorchWithStrengthLevel`](https://developer.android.com/reference/android/hardware/camera2/CameraManager#turnOnTorchWithStrengthLevel(java.lang.String,%20int)). I came along [this](https://blog.esper.io/android-13-flashlight-brightness-control/) by @esper-io and [this](https://9to5google.com/2022/03/01/android-13-flashlight-brightness-control/) blog post.
Would this be a good idea for Flashy?

**Comment by prathamesh-2002** [comment] 2022-10-08 10:40
It would be a handy feature, seems good. I'd like to work on it

**Comment by CrazyMarvin** [comment] 2022-10-08 10:46
> It would be a handy feature, seems good. I'd like to work on it
> 

Awesome! 😎

**Comment by rusty-snake** [comment] 2022-10-15 21:28
FWIW: https://github.com/polodarb/Flashlight-Tiramisu

**Comment by unbiaseduser** [comment] 2022-10-16 15:06
There's a _tiny_ problem...
I can develop it, but _**I cannot test it**_ because I don't have a compatible physical Android 13 device.

**Comment by CrazyMarvin** [comment] 2022-10-16 15:10
I don't have a device running Android 13 too. Maybe we can ship it and let the users test. 😅

**Comment by unbiaseduser** [comment] 2022-10-16 15:27
> I don't have a device running Android 13 too. Maybe we can ship it and let the users test. 😅

b r u h.
Anyway, if we're forced to go that route, maybe you can stick a huge disclaimer for this feature in the release notes for next version?
Something like
> DISCLAIMER: Controlling flashlight brightness is an EXPERIMENTAL feature that is only available in a few devices. If something goes wrong when using this feature, please open an issue. We need detailed explanations, as well as your willingness to test multiple times to properly fix the issue.

**Comment by rusty-snake** [comment] 2022-10-16 15:43
I can test if you give me an apk or some build instructions more detailed than

https://github.com/Crazy-Marvin/Flashy/blob/33a067938c756c3110aa7e57d3995d483dab6177/.github/CONTRIBUTING.md#L1

**Comment by unbiaseduser** [comment] 2022-10-16 18:06
> I can test if you give me an apk or some build instructions more detailed than
> 
> https://github.com/Crazy-Marvin/Flashy/blob/33a067938c756c3110aa7e57d3995d483dab6177/.github/CONTRIBUTING.md#L1

Alright, here's a apk. You can adjust flashlight brightness with the seekbar **if your device supports it otherwise the seekbar stays disabled as before**
Please test every action you can think of, ie. screen rotation, switching modes, etc. and report any weird behavior along with reproduction steps.
[app-debug.zip](https://github.com/Crazy-Marvin/Flashy/files/9795353/app-debug.zip)

Also @CrazyMarvin please update your guidelines lol.

**Comment by rusty-snake** [comment] 2022-10-16 18:40
1. The default brightness (after app (re)start) is 1 (i.e. darkest). I think max brightness would be a better default.
   - This also affects the tile. If flashy is open, the value from the seekbar is used. However if Flashy is closed, the default (i.e. darkest) value is used by the tile. So maybe change the default to 100% and remember the last value.
2. ~Screen light goes "off" when you dimm it to zero, flashlight not. On the one hand this is a bit inconsistent, on the other hand it makes it easier to use the darkest value. And the screen light has wired on/off behaviour if you adjust it.~ I think it's fine the way it is.

Everything else seem to work fine.

---

Other things I noted while playing around and thinking about app functionality:

- darktheme + material you needs some polishing. can be expanded in a new issue.
- is this actually used somewhere? Flashy works fine for me w/o it.
https://github.com/Crazy-Marvin/Flashy/blob/ac47968a84225c1762aae502322e90156755f570/app/src/main/AndroidManifest.xml#L5-L7

**Comment by unbiaseduser** [comment] 2022-10-17 03:57
> The default brightness (after app (re)start) is 1 (i.e. darkest). I think max brightness would be a better default.
    This also affects the tile. If flashy is open, the value from the seekbar is used. However if Flashy is closed, the default (i.e. darkest) value is used by the tile. So maybe change the default to 100% and remember the last value.

Please test this apk. It should have these behaviors:
- If the seekbar is not touched, it should be at max value. The flashlight should be at max brightness as well, in both the app, the qs tile and the widgets.
- If it is adjusted, a setting for the current flash brightness is saved when you release your finger. You can test it by closing and opening the app again (the seekbar should be set at the saved value), as well as measuring the brightness in the app, the tile and the widgets to see if it is correctly set according to the setting.
[app-debug.zip](https://github.com/Crazy-Marvin/Flashy/files/9796684/app-debug.zip)

> darktheme + material you needs some polishing. can be expanded in a new issue.

Please do.

> is this actually used somewhere? Flashy works fine for me w/o it.

There is a widget called "Maximize screen brightness". It works by setting the system's brightness to max (as opposed to the app's brightness in the screen light mode, you can verify this by checking the system brightness bar in quick settings). To do so, the app needs this permission (you'll be prompted for it when adding this widget).

As you can already see, the permission is not used anywhere other than that.

**Comment by rusty-snake** [comment] 2022-10-17 18:28
Seems to work fine now.

**Comment by CrazyMarvin** [comment] 2022-10-17 18:56
> I can test if you give me an apk or some build instructions more detailed than
> 
> https://github.com/Crazy-Marvin/Flashy/blob/33a067938c756c3110aa7e57d3995d483dab6177/.github/CONTRIBUTING.md#L1

I added a little bit more details. 😅  
Please let me know if you miss something.

**Closed as completed** 2022-10-18 07:10 UTC
Labels: enhancement, help wanted, hacktoberfest
